// frontend/src/pages/AssessmentDetail.jsx
import { useEffect, useState }    from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import Header                     from '../components/layout/Header'
import { getTriageWithDetails, deleteTriageLocally } from '../db/localDb'
import { generateReferral }       from '../engine/referralEngine'
import { SYMPTOMS }               from '../shared/triageSchema.js'
import useAppStore                from '../store/useAppStore'
import {
  ChevronLeft, FileText, RefreshCw, Trash2,
  AlertOctagon, AlertTriangle, CheckCircle,
  Building2, Copy, Check, Clock, Calendar,
  CheckSquare, XCircle, HelpCircle
} from 'lucide-react'

const API_BASE = import.meta.env.VITE_API_BASE_URL

// ── Risk config ───────────────────────────────────────────────
const RISK_META = {
  HIGH:      { Icon: AlertOctagon,  bg:'#c8102e', label:'HIGH RISK' },
  MEDIUM:    { Icon: AlertTriangle, bg:'#c45c00', label:'MEDIUM RISK' },
  LOW:       { Icon: CheckCircle,   bg:'#1a6b3a', label:'LOW RISK' },
  immediate: { Icon: AlertOctagon,  bg:'#c8102e', label:'HIGH RISK' },
  priority:  { Icon: AlertTriangle, bg:'#c45c00', label:'MEDIUM RISK' },
  scheduled: { Icon: CheckCircle,   bg:'#1a6b3a', label:'LOW RISK' }
}

// ── Diagnosis status config ───────────────────────────────────
const DIAGNOSIS_OPTIONS = [
  { value: 'no_cancer_identified', label: 'No cancer identified',
    color: '#1a6b3a', bg: '#f0faf4', Icon: CheckCircle },
  { value: 'suspected_cancer',     label: 'Suspected cancer',
    color: '#c45c00', bg: '#fff7ed', Icon: HelpCircle },
  { value: 'confirmed_cancer',     label: 'Cancer confirmed',
    color: '#c8102e', bg: '#fff0f1', Icon: AlertOctagon },
  { value: 'other_condition',      label: 'Other condition identified',
    color: '#0a3d6b', bg: '#e8f0f9', Icon: CheckSquare },
  { value: 'lost_to_followup',     label: 'Lost to follow-up',
    color: '#888', bg: '#f5f5f5', Icon: XCircle },
  { value: 'unknown',              label: 'Unknown / pending',
    color: '#888', bg: '#f5f5f5', Icon: HelpCircle }
]

// ── Referral letter builder ───────────────────────────────────
function buildLetter(record) {
  const ageYears  = Math.floor(record.age_months / 12)
  const ageMos    = record.age_months % 12
  const ageStr    = ageYears > 0
    ? `${ageYears}y ${ageMos > 0 ? `${ageMos}m` : ''}`.trim()
    : `${ageMos} months`
  const genderStr = record.patient_gender && record.patient_gender !== 'unknown'
    ? record.patient_gender.charAt(0).toUpperCase() + record.patient_gender.slice(1)
    : 'Not recorded'
  const date = new Date(record.submitted_at || Date.now())
    .toLocaleDateString('en-GB', { day:'2-digit', month:'long', year:'numeric' })
  const symptomLines = SYMPTOMS
    .filter(s => record.symptoms?.[s.key])
    .map(s => `  • ${s.label} [${s.canonical_code}]`)
    .join('\n') || '  • No symptoms reported'

  return `PAEDIATRIC CANCER TRIAGE REFERRAL LETTER
Generated by Nofom Triage Platform — Schema v1.0.0
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Date of Assessment : ${date}

PATIENT DETAILS
Patient Name       : ${record.patient_name || 'Not provided'}
Age                : ${ageStr}
Gender             : ${genderStr}
${record.facility_name ? `\nASSESSING FACILITY\nFacility           : ${record.facility_name}\n` : ''}
TRIAGE RESULT
Urgency Level      : ${(record.urgency_level || record.risk_level || '—').toUpperCase()}
Risk Score         : ${record.risk_score}
Rule Version       : ${record.rule_version || '1.0.0'}
Assessment Mode    : ${record.assessment_mode || 'rule_based'}

REFERRAL RECOMMENDATION
Action             : ${record.referral_label || '—'}
Timeframe          : ${record.referral_timeframe || '—'}

SYMPTOMS REPORTED (with canonical codes)
${symptomLines}

${record.referral_notes ? `CLINICAL WARNINGS\n${record.referral_notes}\n` : ''}
CLINICAL REASONING
${(record.explanation || []).map((e, i) => `${i + 1}. ${e}`).join('\n\n') || '—'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CLINICAL NOTICE: This letter was generated by a rule-based
triage assistant. It does not constitute a diagnosis. All
referral decisions must be confirmed by a qualified health
professional.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`
}

// ── Delete confirmation ───────────────────────────────────────
function DeleteDialog({ record, onConfirm, onCancel }) {
  return (
    <div style={{
      position:'fixed', inset:0, zIndex:200,
      background:'rgba(10,61,107,0.55)',
      display:'flex', alignItems:'center',
      justifyContent:'center', padding:24
    }}>
      <div style={{
        background:'var(--color-surface)',
        borderRadius:'var(--radius-xl)',
        padding:24, width:'100%', maxWidth:360
      }}>
        <div style={{
          width:48, height:48, borderRadius:'50%',
          background:'var(--color-high-bg)',
          border:'2px solid var(--color-high-border)',
          display:'flex', alignItems:'center',
          justifyContent:'center',
          margin:'0 auto 16px', fontSize:'1.25rem'
        }}>🗑</div>
        <h2 style={{ margin:'0 0 8px', fontSize:'1.0625rem', fontWeight:700,
                     color:'var(--color-text-primary)', textAlign:'center' }}>
          Delete this assessment?
        </h2>
        <p style={{ margin:'0 0 20px', fontSize:'0.875rem',
                    color:'var(--color-text-muted)', textAlign:'center',
                    lineHeight:1.5 }}>
          {record.patient_name && <><strong>{record.patient_name}</strong> · </>}
          {record.urgency_level || record.risk_level} · {' '}
          {new Date(record.submitted_at).toLocaleDateString('en-GB')}
          <br/>
          {record.synced_at
            ? 'This record has been synced and will remain on the server.'
            : '⚠ This record has not been synced and will be permanently lost.'}
        </p>
        <div style={{ display:'flex', gap:10 }}>
          <button onClick={onCancel}
            className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
            Cancel
          </button>
          <button onClick={onConfirm}
            className="nf-btn nf-btn-danger" style={{ flex:1 }}>
            <Trash2 size={15}/> Delete
          </button>
        </div>
      </div>
    </div>
  )
}

// ── Letter drawer ─────────────────────────────────────────────
function LetterDrawer({ record, onClose }) {
  const [copied, setCopied] = useState(false)
  const letter = buildLetter(record)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(letter)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  const handlePrint = () => {
    const w = window.open('', '_blank')
    w.document.write(`<html><head><title>Nofom Referral Letter</title>
      <style>body{font-family:'Courier New',monospace;padding:40px;
      font-size:13px;line-height:1.6;color:#000;}
      pre{white-space:pre-wrap;word-wrap:break-word;}
      @media print{body{padding:20px;}}</style>
      </head><body><pre>${letter}</pre></body></html>`)
    w.document.close()
    w.print()
  }

  return (
    <div style={{
      position:'fixed', inset:0, zIndex:100,
      background:'rgba(10,61,107,0.55)',
      display:'flex', flexDirection:'column', justifyContent:'flex-end'
    }}
      onClick={e => { if (e.target === e.currentTarget) onClose() }}
    >
      <div style={{
        background:'var(--color-surface)',
        borderRadius:'16px 16px 0 0',
        maxHeight:'85dvh', display:'flex',
        flexDirection:'column', overflow:'hidden'
      }}>
        <div style={{
          display:'flex', alignItems:'center',
          justifyContent:'space-between',
          padding:'16px 16px 12px',
          borderBottom:'1px solid var(--color-border)',
          flexShrink:0
        }}>
          <div style={{ display:'flex', alignItems:'center', gap:8 }}>
            <FileText size={16} style={{ color:'var(--color-primary)' }}/>
            <span style={{ fontWeight:700, fontSize:'0.9375rem',
                           color:'var(--color-text-primary)' }}>
              Referral Letter
            </span>
          </div>
          <button onClick={onClose} style={{
            background:'none', border:'none', cursor:'pointer',
            color:'var(--color-text-muted)', fontSize:'1.25rem',
            lineHeight:1, padding:'2px 6px',
            fontFamily:'var(--font-sans)'
          }}>×</button>
        </div>
        <div style={{ flex:1, overflowY:'auto', padding:16 }}>
          <pre style={{
            fontFamily:'"IBM Plex Mono","Courier New",monospace',
            fontSize:'0.75rem', lineHeight:1.7,
            color:'var(--color-text-primary)',
            background:'var(--color-surface-alt)',
            borderRadius:'var(--radius-md)',
            padding:16, whiteSpace:'pre-wrap',
            wordBreak:'break-word', margin:0
          }}>{letter}</pre>
        </div>
        <div style={{
          display:'flex', gap:10,
          padding:'12px 16px 20px',
          borderTop:'1px solid var(--color-border)',
          flexShrink:0
        }}>
          <button onClick={handleCopy}
            className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
            {copied ? <Check size={15}/> : <Copy size={15}/>}
            {copied ? 'Copied!' : 'Copy text'}
          </button>
          <button onClick={handlePrint}
            className="nf-btn nf-btn-primary" style={{ flex:1 }}>
            <FileText size={15}/> Print / PDF
          </button>
        </div>
      </div>
    </div>
  )
}

// ── Follow-up form ────────────────────────────────────────────
function FollowUpTab({ record, session }) {
  // ── Guard: record must be synced before follow-up can be recorded ──
  if (!record.encounter_id) {
    return (
      <div style={{ padding:'24px 0', textAlign:'center' }}>
        <div style={{
          width:56, height:56, borderRadius:'50%',
          background:'var(--color-medium-bg)',
          border:'2px solid var(--color-medium-border)',
          display:'flex', alignItems:'center',
          justifyContent:'center', margin:'0 auto 14px',
          fontSize:'1.5rem'
        }}>
          ⏳
        </div>
        <p style={{ fontWeight:700, fontSize:'1rem',
                    color:'var(--color-text-primary)', margin:'0 0 8px' }}>
          Record not yet synced
        </p>
        <p style={{ fontSize:'0.875rem', color:'var(--color-text-muted)',
                    lineHeight:1.55, maxWidth:280, margin:'0 auto' }}>
          Follow-up can only be recorded after this assessment has synced
          to the server. Connect to the internet and the sync will happen
          automatically.
        </p>
        <div className="nf-alert nf-alert-warning" style={{ marginTop:16, textAlign:'left' }}>
          <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }} />
          <span>
            Once synced, return to this record and the Follow-up tab will be available.
          </span>
        </div>
      </div>
    )
  }

  const [form, setForm] = useState({
    patient_reached:              true,
    referral_completed:           null,
    symptoms_persist:             null,
    diagnosis_status:             '',
    confirmed_diagnosis_label:    '',
    diagnosis_date:               '',
    treatment_started:            null,
    treatment_start_date:         '',
    first_symptom_date:           '',
    first_medical_evaluation_date:'',
    notes:                        ''
  })
  const [submitting, setSubmitting] = useState(false)
  const [submitted,  setSubmitted]  = useState(false)
  const [error,      setError]      = useState('')

  const update = (key, value) => setForm(f => ({ ...f, [key]: value }))

  const ToggleButton = ({ label, value, current, onChange }) => (
    <button
      type="button"
      onClick={() => onChange(value)}
      style={{
        flex:1, padding:'9px 8px',
        border:`1.5px solid ${current === value
          ? 'var(--color-accent)' : 'var(--color-border-strong)'}`,
        borderRadius:'var(--radius-md)',
        background: current === value
          ? 'var(--color-primary-light)' : 'var(--color-surface)',
        color: current === value
          ? 'var(--color-primary)' : 'var(--color-text-secondary)',
        fontFamily:'var(--font-sans)', fontSize:'0.875rem',
        fontWeight: current === value ? 700 : 400,
        cursor:'pointer', transition:'all 120ms'
      }}
    >
      {label}
    </button>
  )

  const handleSubmit = async () => {
    if (!form.diagnosis_status) {
      setError('Please select a diagnosis status.')
      return
    }

    setSubmitting(true)
    setError('')

    try {
      const payload = {
        encounter_id:                  record.encounter_id,
        triage_assessment_id:          record.server_id || null,
        patient_reached:               form.patient_reached,
        referral_completed:           form.referral_completed,
        symptoms_persist:             form.symptoms_persist,
        diagnosis_status:             form.diagnosis_status,
        confirmed_diagnosis_label:    form.confirmed_diagnosis_label || null,
        diagnosis_date:               form.diagnosis_date            || null,
        treatment_started:            form.treatment_started,
        treatment_start_date:         form.treatment_start_date      || null,
        first_symptom_date:           form.first_symptom_date        || null,
        first_medical_evaluation_date: form.first_medical_evaluation_date || null,
        notes:                        form.notes || null
      }

      const res = await fetch(`${API_BASE}/api/followup`, {
        method:  'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization:  `Bearer ${session?.access_token}`
        },
        body: JSON.stringify(payload)
      })

      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed to save follow-up')

      setSubmitted(true)
    } catch (err) {
      setError(err.message)
    } finally {
      setSubmitting(false)
    }
  }

  if (submitted) return (
    <div style={{ padding:'24px 0', textAlign:'center' }}>
      <div style={{
        width:56, height:56, borderRadius:'50%',
        background:'var(--color-low-bg)',
        border:'2px solid var(--color-low-border)',
        display:'flex', alignItems:'center',
        justifyContent:'center', margin:'0 auto 14px'
      }}>
        <CheckCircle size={24} color="var(--color-low)" />
      </div>
      <p style={{ fontWeight:700, fontSize:'1rem',
                  color:'var(--color-text-primary)', margin:'0 0 6px' }}>
        Follow-up recorded
      </p>
      <p style={{ fontSize:'0.875rem', color:'var(--color-text-muted)',
                  margin:0 }}>
        Outcome saved to Supabase and linked to this encounter.
      </p>
    </div>
  )

  return (
    <div style={{ display:'flex', flexDirection:'column', gap:12, paddingBottom:32 }}>

      {/* Patient reached */}
      <div className="nf-card">
        <p style={{ margin:'0 0 10px', fontWeight:600, fontSize:'0.9rem',
                    color:'var(--color-text-primary)' }}>
          Was the patient reached for follow-up?
        </p>
        <div style={{ display:'flex', gap:8 }}>
          <ToggleButton label="Yes" value={true}
            current={form.patient_reached}
            onChange={v => update('patient_reached', v)} />
          <ToggleButton label="No" value={false}
            current={form.patient_reached}
            onChange={v => update('patient_reached', v)} />
        </div>
      </div>

      {/* Referral completed */}
      <div className="nf-card">
        <p style={{ margin:'0 0 10px', fontWeight:600, fontSize:'0.9rem',
                    color:'var(--color-text-primary)' }}>
          Was the referral completed?
        </p>
        <div style={{ display:'flex', gap:8 }}>
          <ToggleButton label="Yes" value={true}
            current={form.referral_completed}
            onChange={v => update('referral_completed', v)} />
          <ToggleButton label="No" value={false}
            current={form.referral_completed}
            onChange={v => update('referral_completed', v)} />
          <ToggleButton label="Unknown" value={null}
            current={form.referral_completed}
            onChange={v => update('referral_completed', v)} />
        </div>
      </div>

      {/* Symptoms persist */}
      <div className="nf-card">
        <p style={{ margin:'0 0 10px', fontWeight:600, fontSize:'0.9rem',
                    color:'var(--color-text-primary)' }}>
          Do symptoms still persist?
        </p>
        <div style={{ display:'flex', gap:8 }}>
          <ToggleButton label="Yes" value={true}
            current={form.symptoms_persist}
            onChange={v => update('symptoms_persist', v)} />
          <ToggleButton label="No" value={false}
            current={form.symptoms_persist}
            onChange={v => update('symptoms_persist', v)} />
          <ToggleButton label="Unknown" value={null}
            current={form.symptoms_persist}
            onChange={v => update('symptoms_persist', v)} />
        </div>
      </div>

      {/* Diagnosis status */}
      <div className="nf-card">
        <p style={{ margin:'0 0 10px', fontWeight:600, fontSize:'0.9rem',
                    color:'var(--color-text-primary)' }}>
          Diagnosis status <span style={{ color:'var(--color-high)' }}>*</span>
        </p>
        <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
          {DIAGNOSIS_OPTIONS.map(opt => {
            const Icon     = opt.Icon
            const selected = form.diagnosis_status === opt.value
            return (
              <label key={opt.value} style={{
                display:'flex', alignItems:'center', gap:10,
                padding:'10px 12px',
                border:`1.5px solid ${selected ? opt.color : 'var(--color-border)'}`,
                borderRadius:'var(--radius-md)',
                background: selected ? opt.bg : 'var(--color-surface)',
                cursor:'pointer', transition:'all 120ms'
              }}>
                <Icon size={16} style={{ color: opt.color, flexShrink:0 }} />
                <span style={{ fontSize:'0.9rem', fontWeight: selected ? 600 : 400,
                               color:'var(--color-text-primary)' }}>
                  {opt.label}
                </span>
                <input type="radio" className="sr-only"
                  checked={selected}
                  onChange={() => update('diagnosis_status', opt.value)} />
              </label>
            )
          })}
        </div>
      </div>

      {/* Confirmed diagnosis label */}
      {(form.diagnosis_status === 'confirmed_cancer' ||
        form.diagnosis_status === 'suspected_cancer') && (
        <div className="nf-card">
          <label className="nf-label">Diagnosis label (if known)</label>
          <input className="nf-input" type="text"
            placeholder="e.g. Acute lymphoblastic leukemia"
            value={form.confirmed_diagnosis_label}
            onChange={e => update('confirmed_diagnosis_label', e.target.value)} />
        </div>
      )}

      {/* Treatment started */}
      {form.diagnosis_status === 'confirmed_cancer' && (
        <div className="nf-card">
          <p style={{ margin:'0 0 10px', fontWeight:600, fontSize:'0.9rem',
                      color:'var(--color-text-primary)' }}>
            Has treatment started?
          </p>
          <div style={{ display:'flex', gap:8 }}>
            <ToggleButton label="Yes" value={true}
              current={form.treatment_started}
              onChange={v => update('treatment_started', v)} />
            <ToggleButton label="No" value={false}
              current={form.treatment_started}
              onChange={v => update('treatment_started', v)} />
          </div>
          {form.treatment_started && (
            <div style={{ marginTop:10 }}>
              <label className="nf-label">Treatment start date</label>
              <input className="nf-input" type="date"
                value={form.treatment_start_date}
                onChange={e => update('treatment_start_date', e.target.value)} />
            </div>
          )}
        </div>
      )}

      {/* Timing indicators */}
      <div className="nf-card">
        <p style={{ margin:'0 0 4px', fontWeight:600, fontSize:'0.9rem',
                    color:'var(--color-text-primary)' }}>
          Timing indicators
        </p>
        <p style={{ margin:'0 0 12px', fontSize:'0.8125rem',
                    color:'var(--color-text-muted)' }}>
          Used to compute parental delay and medical delay metrics.
          Fill in what is known.
        </p>
        <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
          <div>
            <label className="nf-label">First symptom date</label>
            <input className="nf-input" type="date"
              value={form.first_symptom_date}
              onChange={e => update('first_symptom_date', e.target.value)} />
          </div>
          <div>
            <label className="nf-label">First medical evaluation date</label>
            <input className="nf-input" type="date"
              value={form.first_medical_evaluation_date}
              onChange={e => update('first_medical_evaluation_date', e.target.value)} />
          </div>
          {form.diagnosis_status === 'confirmed_cancer' && (
            <div>
              <label className="nf-label">Diagnosis date</label>
              <input className="nf-input" type="date"
                value={form.diagnosis_date}
                onChange={e => update('diagnosis_date', e.target.value)} />
            </div>
          )}
        </div>
      </div>

      {/* Notes */}
      <div className="nf-card">
        <label className="nf-label">Additional notes</label>
        <textarea className="nf-input" rows={3}
          placeholder="Any additional clinical context…"
          value={form.notes}
          onChange={e => update('notes', e.target.value)}
          style={{ resize:'vertical', minHeight:72 }} />
      </div>

      {error && (
        <div className="nf-alert nf-alert-danger">
          <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }} />
          <span>{error}</span>
        </div>
      )}

      <button
        onClick={handleSubmit}
        disabled={submitting || !form.diagnosis_status}
        className="nf-btn nf-btn-primary nf-btn-full nf-btn-large"
      >
        {submitting ? <span className="nf-spinner"/> : null}
        {submitting ? 'Saving…' : 'Record Follow-up Outcome'}
      </button>

    </div>
  )
}

// frontend/src/pages/AssessmentDetail.jsx
// Add this component before the AssessmentDetail function

const AVAILABLE_TESTS = [
  { value: 'cbc',                label: 'Full Blood Count (CBC)',      system: 'hematologic' },
  { value: 'peripheral_smear',   label: 'Peripheral Blood Smear',      system: 'hematologic' },
  { value: 'ultrasound',         label: 'Abdominal Ultrasound',        system: 'abdominal' },
  { value: 'xray',               label: 'Chest X-Ray',                 system: 'respiratory' },
  { value: 'ct_scan',            label: 'CT Scan',                     system: 'general' },
  { value: 'mri',                label: 'MRI',                         system: 'neurologic' },
  { value: 'bone_marrow_biopsy', label: 'Bone Marrow Biopsy',          system: 'hematologic' },
  { value: 'urinalysis',         label: 'Urinalysis',                  system: 'genitourinary' },
  { value: 'lft',                label: 'Liver Function Tests (LFT)',  system: 'abdominal' },
  { value: 'rft',                label: 'Renal Function Tests (RFT)',  system: 'genitourinary' },
  { value: 'other',              label: 'Other (specify in reason)',   system: 'general' },
]

const SYSTEM_COLOR = {
  hematologic:   'var(--color-high)',
  abdominal:     'var(--color-medium)',
  neurologic:    'var(--color-primary)',
  respiratory:   '#0073e6',
  genitourinary: '#6d28d9',
  general:       'var(--color-text-muted)'
}

function DiagnosticsTab({ record, session }) {
  const [selectedTests,    setSelectedTests]    = useState([])
  const [reason,           setReason]           = useState('')
  const [submitting,       setSubmitting]        = useState(false)
  const [submitted,        setSubmitted]         = useState(false)
  const [existing,         setExisting]          = useState([])
  const [loadingExisting,  setLoadingExisting]   = useState(false)
  const [error,            setError]             = useState('')

  useEffect(() => {
    if (!record.encounter_id || !session?.access_token) return
    setLoadingExisting(true)
    fetch(`${API_BASE}/api/diagnostics/encounter/${record.encounter_id}`, {
      headers: { Authorization: `Bearer ${session.access_token}` }
    })
      .then(r => r.json())
      .then(data => setExisting(data.data || []))
      .catch(console.warn)
      .finally(() => setLoadingExisting(false))
  }, [record.encounter_id])

  const toggleTest = (val) => setSelectedTests(prev =>
    prev.includes(val) ? prev.filter(t => t !== val) : [...prev, val]
  )

  // Guard — must be synced
  if (!record.encounter_id) return (
    <div style={{ padding:'32px 16px', textAlign:'center' }}>
      <div style={{
        width:56, height:56, borderRadius:'50%',
        background:'var(--color-medium-bg)',
        border:'2px solid var(--color-medium-border)',
        display:'flex', alignItems:'center', justifyContent:'center',
        margin:'0 auto 14px', fontSize:'1.5rem'
      }}>⏳</div>
      <p style={{ fontWeight:700, fontSize:'1rem',
                  color:'var(--color-text-primary)', margin:'0 0 8px' }}>
        Sync required
      </p>
      <p style={{ fontSize:'0.875rem', color:'var(--color-text-muted)',
                  lineHeight:1.55, maxWidth:280, margin:'0 auto 16px' }}>
        Diagnostic requests are linked to encounters.
        This record must sync before tests can be requested.
      </p>
      <div className="nf-alert nf-alert-warning">
        <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }} />
        <span>Connect to the internet — sync happens automatically.</span>
      </div>
    </div>
  )

  const STATUS_STYLE = {
    pending:      { bg:'var(--color-medium-bg)',  color:'var(--color-medium-text)' },
    completed:    { bg:'var(--color-low-bg)',      color:'var(--color-low-text)'   },
    abnormal:     { bg:'var(--color-high-bg)',     color:'var(--color-high-text)'  },
    normal:       { bg:'var(--color-low-bg)',      color:'var(--color-low-text)'   },
    inconclusive: { bg:'#f5f0ff',                  color:'#6d28d9'                 },
  }

  const handleSubmit = async () => {
    if (selectedTests.length === 0) { setError('Please select at least one test.'); return }
    setSubmitting(true); setError('')
    try {
      const res = await fetch(`${API_BASE}/api/diagnostics`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${session?.access_token}`
        },
        body: JSON.stringify({
          encounter_id:         record.encounter_id,
          triage_assessment_id: record.server_id || null,
          requested_tests:      selectedTests,
          request_reason:       reason || null,
          result_status:        'pending'
        })
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed to submit')
      setSubmitted(true)
      setExisting(prev => [data, ...prev])
    } catch (err) {
      setError(err.message)
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div style={{ display:'flex', flexDirection:'column', gap:12, paddingBottom:32 }}>

      {/* Loading indicator */}
      {loadingExisting && (
        <p style={{ fontSize:'0.875rem', color:'var(--color-text-muted)',
                    textAlign:'center', padding:'12px 0' }}>
          Loading existing requests…
        </p>
      )}

      {/* Existing requests */}
      {existing.length > 0 && (
        <div className="nf-card">
          <p className="nf-section-title" style={{ marginBottom:10 }}>
            Previous Requests ({existing.length})
          </p>
          {existing.map((req, i) => {
            const sc = STATUS_STYLE[req.result_status] || STATUS_STYLE.pending
            return (
              <div key={i} style={{
                padding:'10px 0',
                borderBottom: i < existing.length - 1
                  ? '1px solid var(--color-border)' : 'none',
                display:'flex', justifyContent:'space-between',
                alignItems:'flex-start', gap:8
              }}>
                <div style={{ flex:1 }}>
                  <p style={{ margin:0, fontSize:'0.875rem', fontWeight:600,
                              color:'var(--color-text-primary)' }}>
                    {(req.requested_tests || [])
                      .map(t => AVAILABLE_TESTS.find(at => at.value === t)?.label || t)
                      .join(', ')}
                  </p>
                  {req.request_reason && (
                    <p style={{ margin:'3px 0 0', fontSize:'0.8125rem',
                                color:'var(--color-text-muted)', fontStyle:'italic' }}>
                      {req.request_reason}
                    </p>
                  )}
                </div>
                <span style={{
                  fontSize:'0.75rem', fontWeight:700,
                  padding:'3px 10px', borderRadius:999,
                  background: sc.bg, color: sc.color, flexShrink:0
                }}>
                  {req.result_status}
                </span>
              </div>
            )
          })}
        </div>
      )}

      {/* Form or success state */}
      {submitted ? (
        <div style={{ padding:'32px 16px', textAlign:'center' }}>
          <div style={{
            width:56, height:56, borderRadius:'50%',
            background:'var(--color-low-bg)',
            border:'2px solid var(--color-low-border)',
            display:'flex', alignItems:'center', justifyContent:'center',
            margin:'0 auto 14px'
          }}>
            <CheckCircle size={24} color="var(--color-low)" />
          </div>
          <p style={{ fontWeight:700, fontSize:'1rem',
                      color:'var(--color-text-primary)', margin:'0 0 6px' }}>
            Request submitted
          </p>
          <p style={{ fontSize:'0.875rem', color:'var(--color-text-muted)',
                      margin:'0 0 16px' }}>
            {selectedTests.length} test{selectedTests.length !== 1 ? 's' : ''} requested
            and linked to this encounter.
          </p>
          <button
            onClick={() => { setSubmitted(false); setSelectedTests([]); setReason('') }}
            className="nf-btn nf-btn-secondary"
          >
            Request more tests
          </button>
        </div>
      ) : (
        <>
          {/* Test selection */}
          <div className="nf-card">
            <p style={{ margin:'0 0 4px', fontWeight:600, fontSize:'0.9375rem',
                        color:'var(--color-text-primary)' }}>
              Request Diagnostic Tests
            </p>
            <p style={{ margin:'0 0 14px', fontSize:'0.8125rem',
                        color:'var(--color-text-muted)', lineHeight:1.45 }}>
              Select tests to request at the referral facility.
              Recorded against the encounter for audit and tracking.
            </p>

            <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
              {AVAILABLE_TESTS.map(test => {
                const selected    = selectedTests.includes(test.value)
                const accentColor = SYSTEM_COLOR[test.system] || 'var(--color-text-muted)'
                return (
                  <label
                    key={test.value}
                    style={{
                      display:'flex', alignItems:'center', gap:12,
                      padding:'11px 14px',
                      border:`1.5px solid ${selected
                        ? accentColor : 'var(--color-border)'}`,
                      borderRadius:'var(--radius-md)',
                      background: selected
                        ? 'var(--color-primary-light)' : 'var(--color-surface)',
                      cursor:'pointer', transition:'all 120ms',
                      userSelect:'none', WebkitTapHighlightColor:'transparent'
                    }}
                  >
                    <div style={{
                      flexShrink:0, width:20, height:20,
                      borderRadius:'var(--radius-sm)',
                      border:`2px solid ${selected
                        ? accentColor : 'var(--color-border-strong)'}`,
                      background: selected ? accentColor : 'transparent',
                      display:'flex', alignItems:'center', justifyContent:'center',
                      transition:'all 120ms'
                    }}>
                      {selected && (
                        <svg viewBox="0 0 12 12" width="11" height="11">
                          <path d="M2 6l3 3 5-5" stroke="white" strokeWidth="2"
                                fill="none" strokeLinecap="round"
                                strokeLinejoin="round"/>
                        </svg>
                      )}
                    </div>

                    <span style={{
                      flex:1, fontSize:'0.9375rem',
                      fontWeight: selected ? 600 : 400,
                      color:'var(--color-text-primary)'
                    }}>
                      {test.label}
                    </span>

                    <span style={{
                      fontSize:'0.6875rem', fontWeight:700,
                      color: accentColor,
                      letterSpacing:'0.05em', textTransform:'uppercase',
                      flexShrink:0
                    }}>
                      {test.system}
                    </span>

                    <input type="checkbox" style={{ display:'none' }}
                      checked={selected}
                      onChange={() => toggleTest(test.value)} />
                  </label>
                )
              })}
            </div>
          </div>

          {/* Reason */}
          <div className="nf-card">
            <label className="nf-label">Clinical reason (optional)</label>
            <textarea
              className="nf-input"
              rows={2}
              placeholder="e.g. Suspected leukemia — require CBC to assess bone marrow function"
              value={reason}
              onChange={e => setReason(e.target.value)}
              style={{ resize:'vertical', minHeight:60 }}
            />
          </div>

          {error && (
            <div className="nf-alert nf-alert-danger">
              <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }} />
              <span>{error}</span>
            </div>
          )}

          <button
            onClick={handleSubmit}
            disabled={submitting || selectedTests.length === 0}
            className="nf-btn nf-btn-primary nf-btn-full nf-btn-large"
          >
            {submitting ? <span className="nf-spinner"/> : null}
            {submitting
              ? 'Submitting…'
              : selectedTests.length > 0
                ? `Request ${selectedTests.length} Test${selectedTests.length !== 1 ? 's' : ''} →`
                : 'Select tests above to continue'}
          </button>
        </>
      )}

    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────
export default function AssessmentDetail() {
  const { id }    = useParams()
  const navigate  = useNavigate()
  const { session } = useAppStore()

  const [record,     setRecord]     = useState(null)
  const [loading,    setLoading]    = useState(true)
  const [showLetter, setShowLetter] = useState(false)
  const [showDelete, setShowDelete] = useState(false)
  const [deleting,   setDeleting]   = useState(false)
  const [activeTab,  setActiveTab]  = useState('result')

  useEffect(() => {
    getTriageWithDetails(id)
      .then(r => { if (!r) navigate('/'); setRecord(r) })
      .finally(() => setLoading(false))
  }, [id])

  const handleDelete = async () => {
    setDeleting(true)
    try {
      await deleteTriageLocally(id)
      navigate('/')
    } catch { setDeleting(false); setShowDelete(false) }
  }

  const handleReAssess = () => navigate('/triage/new', {
    state: {
      prefill: {
        patient_name:   record.patient_name,
        patient_gender: record.patient_gender,
        age_months:     record.age_months,
        facility_id:    record.facility_id,
        facility_name:  record.facility_name
      }
    }
  })

  if (loading) return (
    <div className="nf-page"><Header />
      <div style={{ display:'flex', justifyContent:'center', padding:48 }}>
        <p style={{ color:'var(--color-text-muted)', fontSize:'0.875rem' }}>Loading…</p>
      </div>
    </div>
  )

  if (!record) return null

  const riskKey      = record.risk_level || record.urgency_level || 'LOW'
  const meta         = RISK_META[riskKey] || RISK_META.LOW
  const Icon         = meta.Icon
  const ageYears     = Math.floor(record.age_months / 12)
  const ageMos       = record.age_months % 12
  const presentSymptoms = SYMPTOMS.filter(s => record.symptoms?.[s.key])

  const tabStyle = (tab) => ({
    flex:1, padding:'10px 4px', background:'none', border:'none',
    borderBottom: activeTab === tab
      ? '2px solid var(--color-primary)' : '2px solid transparent',
    color: activeTab === tab
      ? 'var(--color-primary)' : 'var(--color-text-muted)',
    fontFamily:'var(--font-sans)', fontSize:'0.8125rem',
    fontWeight: activeTab === tab ? 700 : 400,
    cursor:'pointer', transition:'all 150ms'
  })

  return (
    <div className="nf-page">
      <Header />
      <main className="nf-main">

        <button onClick={() => navigate('/')} style={{
          display:'flex', alignItems:'center', gap:4,
          background:'none', border:'none', cursor:'pointer',
          color:'var(--color-text-muted)', fontSize:'0.875rem',
          fontFamily:'var(--font-sans)', padding:'0 0 14px', fontWeight:500
        }}>
          <ChevronLeft size={15}/> Dashboard
        </button>

        {/* Patient header */}
        <div className="nf-card" style={{ marginBottom:12 }}>
          <div style={{ display:'flex', alignItems:'center',
                        justifyContent:'space-between', marginBottom:10 }}>
            <div style={{ display:'flex', alignItems:'center', gap:10 }}>
              <div style={{
                width:42, height:42, borderRadius:'50%',
                background: meta.bg,
                display:'flex', alignItems:'center',
                justifyContent:'center', flexShrink:0
              }}>
                <Icon size={20} color="white"/>
              </div>
              <div>
                <p style={{ margin:0, fontWeight:700, fontSize:'1rem',
                            color:'var(--color-text-primary)' }}>
                  {record.patient_name || 'Patient'}
                </p>
                <p style={{ margin:'2px 0 0', fontSize:'0.8125rem',
                            color:'var(--color-text-muted)' }}>
                  Age: {ageYears > 0 ? `${ageYears}y ` : ''}{ageMos > 0 ? `${ageMos}m` : ''}
                  {ageYears === 0 && ageMos === 0 ? `${record.age_months} months` : ''}
                  {record.patient_gender && record.patient_gender !== 'unknown'
                    ? ` · ${record.patient_gender.charAt(0).toUpperCase() + record.patient_gender.slice(1)}`
                    : ''}
                </p>
              </div>
            </div>
            <div style={{
              background: meta.bg, color:'white',
              padding:'4px 12px', borderRadius:999,
              fontSize:'0.75rem', fontWeight:700, letterSpacing:'0.05em'
            }}>
              {meta.label}
            </div>
          </div>

          <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
            <span className="nf-chip">
              <Calendar size={11}/>{' '}
              {new Date(record.submitted_at).toLocaleDateString('en-GB', {
                day:'2-digit', month:'short', year:'numeric'
              })}
            </span>
            <span className="nf-chip">Score: {record.risk_score}</span>
            {record.facility_name && (
              <span className="nf-chip">
                <Building2 size={11}/> {record.facility_name}
              </span>
            )}
            <span className="nf-chip" style={{
              background: record.synced_at ? 'var(--color-low-bg)' : 'var(--color-medium-bg)',
              border: `1px solid ${record.synced_at ? 'var(--color-low-border)' : 'var(--color-medium-border)'}`,
              color: record.synced_at ? 'var(--color-low-text)' : 'var(--color-medium-text)'
            }}>
              {record.synced_at ? '✓ Synced' : '● Pending sync'}
            </span>
          </div>
        </div>

        {/* Tabs */}
        <div style={{
          display:'flex', borderBottom:'1px solid var(--color-border)',
          marginBottom:12, gap:0, overflowX:'auto'
        }}>
          <button style={tabStyle('result')}    onClick={() => setActiveTab('result')}>Result</button>
          <button style={tabStyle('referral')}  onClick={() => setActiveTab('referral')}>Referral</button>
          <button style={tabStyle('symptoms')}  onClick={() => setActiveTab('symptoms')}>Symptoms</button>
          <button style={tabStyle('explanation')} onClick={() => setActiveTab('explanation')}>Why?</button>
          <button style={tabStyle('followup')}  onClick={() => setActiveTab('followup')}>
            Follow-up
          </button>

          <button style={tabStyle('diagnostics')} onClick={() => setActiveTab('diagnostics')}>
            Diagnostics
          </button>

        </div>

        {/* Result tab */}
        {activeTab === 'result' && (
          <div>
            <div style={{
              background: meta.bg, borderRadius:'var(--radius-lg)',
              padding:20, color:'white', marginBottom:12,
              position:'relative', overflow:'hidden'
            }}>
              <div style={{
                position:'absolute', top:-30, right:-20,
                width:120, height:120, borderRadius:'50%',
                background:'rgba(255,255,255,0.07)', pointerEvents:'none'
              }}/>
              <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:12 }}>
                <Icon size={32}/>
                <div>
                  <p style={{ margin:0, fontSize:'1.5rem', fontWeight:800,
                              letterSpacing:'-0.02em', lineHeight:1 }}>
                    {meta.label}
                  </p>
                  <p style={{ margin:'4px 0 0', fontSize:'0.9375rem', opacity:0.85 }}>
                    {record.urgency_level || record.risk_level}
                  </p>
                </div>
              </div>
              <div style={{ display:'flex', justifyContent:'space-between',
                            fontSize:'0.75rem', opacity:0.75, marginBottom:5 }}>
                <span>Risk score</span>
                <span style={{ fontFamily:'var(--font-mono)', fontWeight:600 }}>
                  {record.risk_score} / 200
                </span>
              </div>
              <div style={{ height:8, background:'rgba(255,255,255,0.25)',
                            borderRadius:999, overflow:'hidden' }}>
                <div style={{
                  height:'100%', background:'rgba(255,255,255,0.85)',
                  borderRadius:999,
                  width:`${Math.min(100, Math.round((record.risk_score/200)*100))}%`
                }}/>
              </div>
            </div>

            <div className="nf-card">
              <p className="nf-section-title" style={{ marginBottom:10 }}>Score breakdown</p>
              {SYMPTOMS.map(s => {
                const score = record.score_breakdown?.[s.canonical_code]
                           || record.score_breakdown?.[s.key]
                           || 0
                if (score === 0) return null
                return (
                  <div key={s.key} style={{
                    display:'flex', alignItems:'center',
                    justifyContent:'space-between',
                    padding:'7px 0',
                    borderBottom:'1px solid var(--color-border)', gap:8
                  }}>
                    <p style={{ margin:0, fontSize:'0.875rem',
                                color:'var(--color-text-secondary)', flex:1 }}>
                      {s.label}
                    </p>
                    <span style={{ fontFamily:'var(--font-mono)', fontWeight:700,
                                   fontSize:'0.875rem', color:'var(--color-high)',
                                   flexShrink:0 }}>
                      +{score}
                    </span>
                  </div>
                )
              })}
              <p style={{ margin:'10px 0 0', fontSize:'0.8125rem',
                          color:'var(--color-text-muted)' }}>
                Duration: <strong>{record.duration_weeks} week{record.duration_weeks !== 1 ? 's' : ''}</strong>
                {' · '}Prior treatment: <strong>{record.prior_treatment ? 'Yes' : 'No'}</strong>
              </p>
            </div>
          </div>
        )}

        {/* Referral tab */}
        {activeTab === 'referral' && (
          <div className="nf-card" style={{ borderLeft:`4px solid ${meta.bg}` }}>
            <div style={{ display:'flex', alignItems:'flex-start',
                          gap:10, marginBottom:14 }}>
              <Building2 size={18} style={{ color:meta.bg, flexShrink:0, marginTop:2 }}/>
              <div>
                <p style={{ margin:0, fontWeight:700, fontSize:'1rem',
                            color:'var(--color-text-primary)' }}>
                  {record.referral_label || '—'}
                </p>
                <p style={{ margin:'5px 0 3px', fontSize:'0.9375rem',
                            color:'var(--color-text-secondary)' }}>
                  ⏱ {record.referral_timeframe || '—'}
                </p>
              </div>
            </div>
            {record.referral_notes && (
              <div className="nf-alert nf-alert-danger" style={{ marginBottom:12 }}>
                <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }}/>
                <span style={{ fontWeight:600 }}>{record.referral_notes}</span>
              </div>
            )}
            {(() => {
              const ref = generateReferral(
                { urgency_level: record.urgency_level || 'scheduled',
                  urgency_color: record.urgency_color || 'green' },
                record.symptoms || {}
              )
              return (
                <div>
                  <p className="nf-section-title" style={{ marginBottom:8 }}>Steps to take</p>
                  {ref.instructions.map((step, i) => (
                    <div key={i} style={{
                      display:'flex', gap:10, padding:'9px 0',
                      borderBottom:'1px solid var(--color-border)',
                      alignItems:'flex-start'
                    }}>
                      <div style={{
                        flexShrink:0, width:24, height:24, borderRadius:'50%',
                        background:'var(--color-primary-light)',
                        color:'var(--color-primary)',
                        fontSize:'0.8125rem', fontWeight:700,
                        display:'flex', alignItems:'center', justifyContent:'center'
                      }}>{i+1}</div>
                      <p style={{ margin:0, fontSize:'0.9rem',
                                  color:'var(--color-text-secondary)',
                                  lineHeight:1.55, flex:1 }}>
                        {step}
                      </p>
                    </div>
                  ))}
                </div>
              )
            })()}
          </div>
        )}

        {/* Symptoms tab */}
        {activeTab === 'symptoms' && (
          <div className="nf-card">
            {presentSymptoms.length === 0 ? (
              <p style={{ color:'var(--color-text-muted)', fontSize:'0.875rem',
                          padding:'8px 0' }}>
                No symptoms recorded.
              </p>
            ) : (
              <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                {presentSymptoms.map(s => (
                  <div key={s.key} style={{
                    padding:'10px 12px',
                    background:'var(--color-high-bg)',
                    border:`1px solid var(--color-high-border)`,
                    borderRadius:'var(--radius-md)'
                  }}>
                    <p style={{ margin:0, fontWeight:600, fontSize:'0.9rem',
                                color:'var(--color-high-text)' }}>
                      {s.label}
                    </p>
                    <p style={{ margin:'3px 0 0', fontSize:'0.75rem',
                                color:'var(--color-text-muted)',
                                fontFamily:'var(--font-mono)' }}>
                      {s.canonical_code}
                    </p>
                    {s.is_red_flag && (
                      <span style={{ fontSize:'0.6875rem', fontWeight:700,
                                     color:'var(--color-high)', letterSpacing:'0.04em' }}>
                        ● RED FLAG
                      </span>
                    )}
                  </div>
                ))}
              </div>
            )}
            <div style={{ marginTop:14, padding:'10px 12px',
                          background:'var(--color-surface-alt)',
                          borderRadius:'var(--radius-md)' }}>
              <p style={{ margin:0, fontSize:'0.8125rem', color:'var(--color-text-muted)' }}>
                Duration: <strong>{record.duration_weeks} week{record.duration_weeks !== 1 ? 's' : ''}</strong>
                {' · '}Prior treatment: <strong>{record.prior_treatment ? 'Yes' : 'No'}</strong>
              </p>
            </div>
          </div>
        )}

        {/* Why? tab */}
        {activeTab === 'explanation' && (
          <div className="nf-card">
            {(record.explanation || []).map((line, i) => (
              <div key={i} style={{
                display:'flex', gap:10, padding:'9px 0',
                borderBottom:'1px solid var(--color-border)',
                alignItems:'flex-start'
              }}>
                <div style={{
                  flexShrink:0, width:6, height:6, borderRadius:'50%',
                  background:'var(--color-primary)', opacity:0.4, marginTop:8
                }}/>
                <p style={{ margin:0, fontSize:'0.9rem',
                            color:'var(--color-text-secondary)',
                            lineHeight:1.6, flex:1 }}>
                  {line}
                </p>
              </div>
            ))}
            <div className="nf-disclaimer" style={{ marginTop:12 }}>
              <strong>Clinical note:</strong> This tool assists decision-making
              and does not replace clinical judgement.
            </div>
          </div>
        )}

        {/* Follow-up tab */}
        {activeTab === 'followup' && (
          <FollowUpTab record={record} session={session} />
        )}

        <div style={{ height:16 }}/>
      </main>

        {/* Diagnostics tab */}
        {activeTab === 'diagnostics' && (
          <DiagnosticsTab record={record} session={session} />
        )}

      {/* Action bar — hide on tabs that have their own submit buttons */}
      {activeTab !== 'diagnostics' && activeTab !== 'followup' && (
        <div className="nf-sticky-bar">
          <div className="nf-sticky-bar-inner">
            <div style={{ display:'flex', gap:8 }}>
              <button onClick={() => setShowLetter(true)}
                className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
                <FileText size={15}/> Letter
              </button>
              <button onClick={handleReAssess}
                className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
                <RefreshCw size={15}/> Re-assess
              </button>
              <button onClick={() => setShowDelete(true)} style={{
                display:'flex', alignItems:'center', justifyContent:'center',
                gap:6, padding:'12px 14px',
                background:'var(--color-high-bg)',
                border:'1.5px solid var(--color-high-border)',
                borderRadius:'var(--radius-md)',
                color:'var(--color-high)', fontFamily:'var(--font-sans)',
                fontWeight:600, fontSize:'0.875rem', cursor:'pointer'
              }}>
                <Trash2 size={15}/>
              </button>
            </div>
          </div>
        </div>
      )}
      {/* Action bar */}
      <div className="nf-sticky-bar">
        <div className="nf-sticky-bar-inner">
          <div style={{ display:'flex', gap:8 }}>
            <button onClick={() => setShowLetter(true)}
              className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
              <FileText size={15}/> Letter
            </button>
            <button onClick={handleReAssess}
              className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
              <RefreshCw size={15}/> Re-assess
            </button>
            <button onClick={() => setShowDelete(true)} style={{
              display:'flex', alignItems:'center', justifyContent:'center',
              gap:6, padding:'12px 14px',
              background:'var(--color-high-bg)',
              border:`1.5px solid var(--color-high-border)`,
              borderRadius:'var(--radius-md)',
              color:'var(--color-high)', fontFamily:'var(--font-sans)',
              fontWeight:600, fontSize:'0.875rem', cursor:'pointer'
            }}>
              <Trash2 size={15}/>
            </button>
          </div>
        </div>
      </div>

      {showLetter && <LetterDrawer record={record} onClose={() => setShowLetter(false)}/>}
      {showDelete && (
        <DeleteDialog record={record}
          onConfirm={handleDelete}
          onCancel={() => setShowDelete(false)}/>
      )}
    </div>
  )
}
