// frontend/src/pages/AssessmentDetail.jsx
import { useEffect, useState }   from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import Header                    from '../components/layout/Header'
import { getTriageWithDetails, deleteTriageLocally } from '../db/localDb'
import { generateReferral }      from '../engine/referralEngine'
import { SYMPTOMS }              from '../../shared/triageSchema.js'
import {
  ChevronLeft, FileText, RefreshCw, Trash2,
  AlertOctagon, AlertTriangle, CheckCircle,
  Building2, Copy, Check, X, Clock,
  User, Calendar
} from 'lucide-react'

// ── Risk config ───────────────────────────────────────────────
const RISK_META = {
  HIGH:   { Icon: AlertOctagon,  bg:'#c8102e', label:'HIGH RISK',   sub:'Urgent referral required' },
  MEDIUM: { Icon: AlertTriangle, bg:'#c45c00', label:'MEDIUM RISK', sub:'Referral recommended' },
  LOW:    { Icon: CheckCircle,   bg:'#1a6b3a', label:'LOW RISK',    sub:'Monitor and educate' }
}

// ── Referral letter builder ───────────────────────────────────
function buildLetter(record) {
  const ageYears = Math.floor(record.age_months / 12)
  const ageMos   = record.age_months % 12
  const ageStr   = ageYears > 0
    ? `${ageYears}y ${ageMos > 0 ? `${ageMos}m` : ''}`.trim()
    : `${ageMos} months`

  const genderStr = record.patient_gender && record.patient_gender !== 'unknown'
    ? record.patient_gender.charAt(0).toUpperCase() + record.patient_gender.slice(1)
    : 'Not recorded'

  const date = new Date(record.submitted_at || Date.now())
    .toLocaleDateString('en-GB', { day:'2-digit', month:'long', year:'numeric' })

  const symptomLines = SYMPTOMS
    .filter(s => record.symptoms?.[s.key])
    .map(s => `  • ${s.label}`)
    .join('\n') || '  • No symptoms reported'

  const referral = record.referral_label
    ? {
        label:        record.referral_label,
        timeframe:    record.referral_timeframe,
        facility_tier: record.referral_facility_tier || '—',
        special_notes: record.referral_notes
          ? record.referral_notes.split(' | ')
          : []
      }
    : null

  return `PAEDIATRIC CANCER TRIAGE REFERRAL LETTER
Generated by Nofom Triage Platform
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Date of Assessment : ${date}

PATIENT DETAILS
Patient Name       : ${record.patient_name || 'Not provided'}
Age                : ${ageStr}
Gender             : ${genderStr}

${record.facility_name
  ? `ASSESSING FACILITY\nFacility           : ${record.facility_name}\n`
  : ''}
TRIAGE RESULT
Risk Level         : ${record.risk_level}
Risk Score         : ${record.risk_score}
Assessed by        : Nofom Rule-Based Triage Engine v1

${referral ? `REFERRAL RECOMMENDATION
Action             : ${referral.label}
Timeframe          : ${referral.timeframe}
Facility Tier      : ${referral.facility_tier}
` : ''}
SYMPTOMS REPORTED
${symptomLines}

${referral?.special_notes?.length > 0
  ? `CLINICAL WARNINGS\n${referral.special_notes.map(n => `  ⚠ ${n}`).join('\n')}\n`
  : ''}
CLINICAL REASONING
${record.explanation?.map((e, i) => `${i + 1}. ${e}`).join('\n\n') || '—'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CLINICAL NOTICE: This letter was generated by a rule-based
triage assistant. It does not constitute a diagnosis. All
referral decisions must be confirmed by a qualified health
professional.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`
}

// ── Delete confirmation dialog ────────────────────────────────
function DeleteDialog({ record, onConfirm, onCancel }) {
  return (
    <div style={{
      position:'fixed', inset:0, zIndex:200,
      background:'rgba(10,61,107,0.55)',
      display:'flex', alignItems:'center', justifyContent:'center',
      padding:24
    }}>
      <div style={{
        background:'var(--color-surface)',
        borderRadius:'var(--radius-xl)',
        padding:24, width:'100%', maxWidth:360
      }}>
        <div style={{
          width:48, height:48, borderRadius:'50%',
          background:'var(--color-high-bg)',
          border:'2px solid var(--color-high-border)',
          display:'flex', alignItems:'center', justifyContent:'center',
          margin:'0 auto 16px', fontSize:'1.25rem'
        }}>
          🗑
        </div>
        <h2 style={{ margin:'0 0 8px', fontSize:'1.0625rem', fontWeight:700,
                     color:'var(--color-text-primary)', textAlign:'center' }}>
          Delete this assessment?
        </h2>
        <p style={{ margin:'0 0 20px', fontSize:'0.875rem',
                    color:'var(--color-text-muted)', textAlign:'center',
                    lineHeight:1.5 }}>
          {record.patient_name
            ? <><strong>{record.patient_name}</strong> · </>
            : null}
          {record.risk_level} risk · {new Date(record.submitted_at)
            .toLocaleDateString('en-GB')}
          <br/>
          {record.synced_at
            ? 'This record has been synced to the server and will remain there.'
            : '⚠ This record has not been synced and will be permanently lost.'}
        </p>
        <div style={{ display:'flex', gap:10 }}>
          <button
            onClick={onCancel}
            className="nf-btn nf-btn-secondary"
            style={{ flex:1 }}
          >
            Cancel
          </button>
          <button
            onClick={onConfirm}
            className="nf-btn nf-btn-danger"
            style={{ flex:1 }}
          >
            <Trash2 size={15} /> Delete
          </button>
        </div>
      </div>
    </div>
  )
}

// ── Referral letter drawer ────────────────────────────────────
function LetterDrawer({ record, onClose }) {
  const [copied, setCopied] = useState(false)
  const letter = buildLetter(record)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(letter)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  const handlePrint = () => {
    const w = window.open('', '_blank')
    w.document.write(`<html><head><title>Nofom Referral Letter</title>
      <style>
        body { font-family: 'Courier New', monospace; padding:40px;
               font-size:13px; line-height:1.6; color:#000; }
        pre  { white-space:pre-wrap; word-wrap:break-word; }
        @media print { body { padding:20px; } }
      </style></head><body><pre>${letter}</pre></body></html>`)
    w.document.close()
    w.print()
  }

  return (
    <div
      style={{
        position:'fixed', inset:0, zIndex:100,
        background:'rgba(10,61,107,0.55)',
        display:'flex', flexDirection:'column',
        justifyContent:'flex-end'
      }}
      onClick={e => { if (e.target === e.currentTarget) onClose() }}
    >
      <div style={{
        background:'var(--color-surface)',
        borderRadius:'16px 16px 0 0',
        maxHeight:'85dvh', display:'flex',
        flexDirection:'column', overflow:'hidden'
      }}>
        <div style={{
          display:'flex', alignItems:'center',
          justifyContent:'space-between',
          padding:'16px 16px 12px',
          borderBottom:'1px solid var(--color-border)',
          flexShrink:0
        }}>
          <div style={{ display:'flex', alignItems:'center', gap:8 }}>
            <FileText size={16} style={{ color:'var(--color-primary)' }} />
            <span style={{ fontWeight:700, fontSize:'0.9375rem',
                           color:'var(--color-text-primary)' }}>
              Referral Letter
            </span>
          </div>
          <button onClick={onClose} style={{
            background:'none', border:'none', cursor:'pointer',
            color:'var(--color-text-muted)', fontSize:'1.25rem',
            lineHeight:1, padding:'2px 6px',
            fontFamily:'var(--font-sans)'
          }}>×</button>
        </div>

        <div style={{ flex:1, overflowY:'auto', padding:16 }}>
          <pre style={{
            fontFamily:'"IBM Plex Mono","Courier New",monospace',
            fontSize:'0.75rem', lineHeight:1.7,
            color:'var(--color-text-primary)',
            background:'var(--color-surface-alt)',
            borderRadius:'var(--radius-md)',
            padding:16, whiteSpace:'pre-wrap',
            wordBreak:'break-word', margin:0
          }}>
            {letter}
          </pre>
        </div>

        <div style={{
          display:'flex', gap:10,
          padding:'12px 16px 20px',
          borderTop:'1px solid var(--color-border)',
          flexShrink:0
        }}>
          <button onClick={handleCopy}
            className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
            {copied ? <Check size={15}/> : <Copy size={15}/>}
            {copied ? 'Copied!' : 'Copy text'}
          </button>
          <button onClick={handlePrint}
            className="nf-btn nf-btn-primary" style={{ flex:1 }}>
            <FileText size={15}/> Print / PDF
          </button>
        </div>
      </div>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────
export default function AssessmentDetail() {
  const { id }   = useParams()
  const navigate = useNavigate()

  const [record,      setRecord]      = useState(null)
  const [loading,     setLoading]     = useState(true)
  const [showLetter,  setShowLetter]  = useState(false)
  const [showDelete,  setShowDelete]  = useState(false)
  const [deleting,    setDeleting]    = useState(false)
  const [activeTab,   setActiveTab]   = useState('result')
  // activeTab: 'result' | 'referral' | 'explanation'

  useEffect(() => {
    getTriageWithDetails(id)
      .then(r => {
        if (!r) navigate('/')
        setRecord(r)
      })
      .finally(() => setLoading(false))
  }, [id])

  const handleDelete = async () => {
    setDeleting(true)
    try {
      await deleteTriageLocally(id)
      navigate('/')
    } catch (err) {
      console.error('Delete failed:', err)
      setDeleting(false)
      setShowDelete(false)
    }
  }

  const handleReAssess = () => {
    // Navigate to new triage — NewTriage will pick up pre-fill from state
    navigate('/triage/new', {
      state: {
        prefill: {
          patient_name:   record.patient_name,
          patient_gender: record.patient_gender,
          age_months:     record.age_months,
          facility_id:    record.facility_id,
          facility_name:  record.facility_name
        }
      }
    })
  }

  if (loading) return (
    <div className="nf-page">
      <Header />
      <div style={{ display:'flex', justifyContent:'center', padding:48 }}>
        <p style={{ color:'var(--color-text-muted)', fontSize:'0.875rem' }}>
          Loading…
        </p>
      </div>
    </div>
  )

  if (!record) return null

  const meta         = RISK_META[record.risk_level] || RISK_META.LOW
  const Icon         = meta.Icon
  const ageYears     = Math.floor(record.age_months / 12)
  const ageMos       = record.age_months % 12
  const presentSymptoms = SYMPTOMS.filter(s => record.symptoms?.[s.key])

  const TAB_STYLE = (tab) => ({
    flex:1, padding:'9px 4px',
    background:'none', border:'none',
    borderBottom: activeTab === tab
      ? `2px solid var(--color-primary)`
      : '2px solid transparent',
    color: activeTab === tab
      ? 'var(--color-primary)'
      : 'var(--color-text-muted)',
    fontFamily:'var(--font-sans)',
    fontSize:'0.875rem', fontWeight: activeTab === tab ? 700 : 400,
    cursor:'pointer', transition:'all 150ms'
  })

  return (
    <div className="nf-page">
      <Header />

      <main className="nf-main">

        {/* Back */}
        <button onClick={() => navigate('/')} style={{
          display:'flex', alignItems:'center', gap:4,
          background:'none', border:'none', cursor:'pointer',
          color:'var(--color-text-muted)', fontSize:'0.875rem',
          fontFamily:'var(--font-sans)', padding:'0 0 14px', fontWeight:500
        }}>
          <ChevronLeft size={15}/> Dashboard
        </button>

        {/* Patient header card */}
        <div className="nf-card" style={{ marginBottom:12 }}>
          <div style={{ display:'flex', alignItems:'center',
                        justifyContent:'space-between', marginBottom:10 }}>
            <div style={{ display:'flex', alignItems:'center', gap:10 }}>
              <div style={{
                width:42, height:42, borderRadius:'50%',
                background: meta.bg,
                display:'flex', alignItems:'center',
                justifyContent:'center', flexShrink:0
              }}>
                <Icon size={20} color="white"/>
              </div>
              <div>
                <p style={{ margin:0, fontWeight:700, fontSize:'1rem',
                            color:'var(--color-text-primary)' }}>
                  {record.patient_name || 'Patient'}
                </p>
                <p style={{ margin:'2px 0 0', fontSize:'0.8125rem',
                            color:'var(--color-text-muted)' }}>
                  Age: {ageYears > 0 ? `${ageYears}y ` : ''}{ageMos > 0 ? `${ageMos}m` : ''}
                  {ageYears === 0 && ageMos === 0 ? `${record.age_months} months` : ''}
                  {record.patient_gender && record.patient_gender !== 'unknown'
                    ? ` · ${record.patient_gender.charAt(0).toUpperCase() + record.patient_gender.slice(1)}`
                    : ''}
                </p>
              </div>
            </div>
            {/* Risk pill */}
            <div style={{
              background: meta.bg, color:'white',
              padding:'4px 12px', borderRadius:999,
              fontSize:'0.75rem', fontWeight:700,
              letterSpacing:'0.05em'
            }}>
              {record.risk_level}
            </div>
          </div>

          {/* Meta row */}
          <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
            <span className="nf-chip">
              <Calendar size={11}/> {new Date(record.submitted_at)
                .toLocaleDateString('en-GB', {
                  day:'2-digit', month:'short', year:'numeric'
                })}
            </span>
            <span className="nf-chip">
              Score: {record.risk_score}
            </span>
            {record.facility_name && (
              <span className="nf-chip">
                <Building2 size={11}/> {record.facility_name}
              </span>
            )}
            <span className="nf-chip" style={{
              background: record.synced_at
                ? 'var(--color-low-bg)'
                : 'var(--color-medium-bg)',
              border: `1px solid ${record.synced_at
                ? 'var(--color-low-border)'
                : 'var(--color-medium-border)'}`,
              color: record.synced_at
                ? 'var(--color-low-text)'
                : 'var(--color-medium-text)'
            }}>
              {record.synced_at ? '✓ Synced' : '● Pending sync'}
            </span>
          </div>
        </div>

        {/* Tabs */}
        <div style={{
          display:'flex',
          borderBottom:'1px solid var(--color-border)',
          marginBottom:12, gap:0
        }}>
          <button style={TAB_STYLE('result')}
            onClick={() => setActiveTab('result')}>
            Result
          </button>
          <button style={TAB_STYLE('referral')}
            onClick={() => setActiveTab('referral')}>
            Referral
          </button>
          <button style={TAB_STYLE('symptoms')}
            onClick={() => setActiveTab('symptoms')}>
            Symptoms
          </button>
          <button style={TAB_STYLE('explanation')}
            onClick={() => setActiveTab('explanation')}>
            Why?
          </button>
        </div>

        {/* ── Tab: Result ───────────────────────────────── */}
        {activeTab === 'result' && (
          <div>
            {/* Risk badge */}
            <div style={{
              background: meta.bg, borderRadius:'var(--radius-lg)',
              padding:20, color:'white', marginBottom:12,
              position:'relative', overflow:'hidden'
            }}>
              <div style={{
                position:'absolute', top:-30, right:-20,
                width:120, height:120, borderRadius:'50%',
                background:'rgba(255,255,255,0.07)',
                pointerEvents:'none'
              }}/>
              <div style={{ display:'flex', alignItems:'center',
                            gap:12, marginBottom:12 }}>
                <Icon size={32}/>
                <div>
                  <p style={{ margin:0, fontSize:'1.5rem', fontWeight:800,
                              letterSpacing:'-0.02em', lineHeight:1 }}>
                    {meta.label}
                  </p>
                  <p style={{ margin:'4px 0 0', fontSize:'0.9375rem', opacity:0.85 }}>
                    {meta.sub}
                  </p>
                </div>
              </div>
              <div style={{ display:'flex', justifyContent:'space-between',
                            fontSize:'0.75rem', opacity:0.75, marginBottom:5 }}>
                <span>Risk score</span>
                <span style={{ fontFamily:'var(--font-mono)', fontWeight:600 }}>
                  {record.risk_score} / 200
                </span>
              </div>
              <div style={{ height:8, background:'rgba(255,255,255,0.25)',
                            borderRadius:999, overflow:'hidden' }}>
                <div style={{
                  height:'100%', background:'rgba(255,255,255,0.85)',
                  borderRadius:999,
                  width:`${Math.min(100, Math.round((record.risk_score/200)*100))}%`
                }}/>
              </div>
            </div>

            {/* Score breakdown */}
            <div className="nf-card">
              <p className="nf-section-title" style={{ marginBottom:10 }}>
                Score breakdown
              </p>
              {SYMPTOMS.map(s => {
                const score = record.score_breakdown?.[s.key] || 0
                if (score === 0) return null
                return (
                  <div key={s.key} style={{
                    display:'flex', alignItems:'center',
                    justifyContent:'space-between',
                    padding:'7px 0',
                    borderBottom:'1px solid var(--color-border)',
                    gap:8
                  }}>
                    <p style={{ margin:0, fontSize:'0.875rem',
                                color:'var(--color-text-secondary)',
                                flex:1 }}>
                      {s.label}
                    </p>
                    <span style={{
                      fontFamily:'var(--font-mono)', fontWeight:700,
                      fontSize:'0.875rem', color:'var(--color-high)',
                      flexShrink:0
                    }}>
                      +{score}
                    </span>
                  </div>
                )
              })}
              {/* Duration + age */}
              <div style={{ padding:'7px 0',
                            borderBottom:'1px solid var(--color-border)',
                            display:'flex', justifyContent:'space-between' }}>
                <p style={{ margin:0, fontSize:'0.875rem',
                            color:'var(--color-text-secondary)' }}>
                  Duration: {record.duration_weeks} week{record.duration_weeks !== 1 ? 's' : ''}
                </p>
              </div>
              {record.override_applied && (
                <div className="nf-alert nf-alert-warning" style={{ marginTop:10 }}>
                  <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }}/>
                  <span>Safety override applied — 2+ primary indicators
                    forced HIGH risk.</span>
                </div>
              )}
            </div>
          </div>
        )}

        {/* ── Tab: Referral ─────────────────────────────── */}
        {activeTab === 'referral' && (
          <div>
            <div className="nf-card" style={{
              borderLeft:`4px solid ${meta.bg}`,
              marginBottom:12
            }}>
              <div style={{ display:'flex', alignItems:'flex-start',
                            gap:10, marginBottom:14 }}>
                <Building2 size={18} style={{ color:meta.bg,
                  flexShrink:0, marginTop:2 }}/>
                <div>
                  <p style={{ margin:0, fontWeight:700, fontSize:'1rem',
                              color:'var(--color-text-primary)' }}>
                    {record.referral_label || '—'}
                  </p>
                  <p style={{ margin:'5px 0 3px', fontSize:'0.9375rem',
                              color:'var(--color-text-secondary)' }}>
                    ⏱ {record.referral_timeframe || '—'}
                  </p>
                </div>
              </div>

              {/* Special notes from DB */}
              {record.referral_notes && (
                <div className="nf-alert nf-alert-danger"
                  style={{ marginBottom:12 }}>
                  <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }}/>
                  <span style={{ fontWeight:600 }}>{record.referral_notes}</span>
                </div>
              )}

              {/* Regenerate full referral for instructions */}
              {(() => {
                const ref = generateReferral(
                  { risk_level: record.risk_level },
                  record.symptoms || {}
                )
                return (
                  <div>
                    <p className="nf-section-title" style={{ marginBottom:8 }}>
                      Steps to take
                    </p>
                    {ref.instructions.map((step, i) => (
                      <div key={i} style={{
                        display:'flex', gap:10, padding:'9px 0',
                        borderBottom:'1px solid var(--color-border)',
                        alignItems:'flex-start'
                      }}>
                        <div style={{
                          flexShrink:0, width:24, height:24,
                          borderRadius:'50%',
                          background:'var(--color-primary-light)',
                          color:'var(--color-primary)',
                          fontSize:'0.8125rem', fontWeight:700,
                          display:'flex', alignItems:'center',
                          justifyContent:'center'
                        }}>
                          {i+1}
                        </div>
                        <p style={{ margin:0, fontSize:'0.9rem',
                                    color:'var(--color-text-secondary)',
                                    lineHeight:1.55, flex:1 }}>
                          {step}
                        </p>
                      </div>
                    ))}
                  </div>
                )
              })()}
            </div>
          </div>
        )}

        {/* ── Tab: Symptoms ─────────────────────────────── */}
        {activeTab === 'symptoms' && (
          <div className="nf-card">
            {presentSymptoms.length === 0 ? (
              <p style={{ color:'var(--color-text-muted)', fontSize:'0.875rem',
                          padding:'8px 0' }}>
                No symptoms were recorded for this assessment.
              </p>
            ) : (
              <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                {presentSymptoms.map(s => (
                  <div key={s.key} style={{
                    padding:'10px 12px',
                    background:'var(--color-high-bg)',
                    border:`1px solid var(--color-high-border)`,
                    borderRadius:'var(--radius-md)'
                  }}>
                    <p style={{ margin:0, fontWeight:600, fontSize:'0.9rem',
                                color:'var(--color-high-text)' }}>
                      {s.label}
                    </p>
                    {s.isPrimary && (
                      <span style={{ fontSize:'0.6875rem', fontWeight:700,
                                     color:'var(--color-high)',
                                     letterSpacing:'0.04em' }}>
                        ● PRIMARY INDICATOR
                      </span>
                    )}
                  </div>
                ))}
              </div>
            )}

            <div style={{ marginTop:14, padding:'10px 12px',
                          background:'var(--color-surface-alt)',
                          borderRadius:'var(--radius-md)' }}>
              <p style={{ margin:0, fontSize:'0.8125rem',
                          color:'var(--color-text-muted)' }}>
                Duration: <strong>{record.duration_weeks} week{record.duration_weeks !== 1 ? 's' : ''}</strong>
                {' · '}
                Prior treatment: <strong>{record.prior_treatment ? 'Yes' : 'No'}</strong>
              </p>
            </div>
          </div>
        )}

        {/* ── Tab: Explanation ──────────────────────────── */}
        {activeTab === 'explanation' && (
          <div className="nf-card">
            {(record.explanation || []).map((line, i) => (
              <div key={i} style={{
                display:'flex', gap:10, padding:'9px 0',
                borderBottom:'1px solid var(--color-border)',
                alignItems:'flex-start'
              }}>
                <div style={{
                  flexShrink:0, width:6, height:6,
                  borderRadius:'50%', background:'var(--color-primary)',
                  opacity:0.4, marginTop:8
                }}/>
                <p style={{ margin:0, fontSize:'0.9rem',
                            color:'var(--color-text-secondary)',
                            lineHeight:1.6, flex:1 }}>
                  {line}
                </p>
              </div>
            ))}

            <div className="nf-disclaimer" style={{ marginTop:12 }}>
              <strong>Clinical note:</strong> This tool assists decision-making
              and does not replace clinical judgement.
            </div>
          </div>
        )}

        {/* Bottom spacer */}
        <div style={{ height:16 }}/>
      </main>

      {/* ── Action bar ───────────────────────────────────── */}
      <div className="nf-sticky-bar">
        <div className="nf-sticky-bar-inner">
          <div style={{ display:'flex', gap:8, marginBottom:8 }}>
            {/* Generate letter */}
            <button
              onClick={() => setShowLetter(true)}
              className="nf-btn nf-btn-secondary"
              style={{ flex:1 }}
            >
              <FileText size={15}/> Letter
            </button>

            {/* Re-assess */}
            <button
              onClick={handleReAssess}
              className="nf-btn nf-btn-secondary"
              style={{ flex:1 }}
            >
              <RefreshCw size={15}/> Re-assess
            </button>

            {/* Delete */}
            <button
              onClick={() => setShowDelete(true)}
              style={{
                display:'flex', alignItems:'center', justifyContent:'center',
                gap:6, padding:'12px 14px',
                background:'var(--color-high-bg)',
                border:`1.5px solid var(--color-high-border)`,
                borderRadius:'var(--radius-md)',
                color:'var(--color-high)', fontFamily:'var(--font-sans)',
                fontWeight:600, fontSize:'0.875rem', cursor:'pointer'
              }}
            >
              <Trash2 size={15}/>
            </button>
          </div>
        </div>
      </div>

      {/* Drawers and dialogs */}
      {showLetter && (
        <LetterDrawer record={record} onClose={() => setShowLetter(false)}/>
      )}
      {showDelete && (
        <DeleteDialog
          record={record}
          onConfirm={handleDelete}
          onCancel={() => setShowDelete(false)}
        />
      )}
    </div>
  )
}
