// frontend/src/pages/TriageResult.jsx
import { useEffect, useRef, useState, useCallback } from 'react'
import { useNavigate }  from 'react-router-dom'
import Header           from '../components/layout/Header'
import useAppStore      from '../store/useAppStore'
import {
  AlertOctagon, AlertTriangle, CheckCircle,
  Building2, ChevronLeft, ChevronRight,
  PlusCircle, ArrowLeft, FileText, Copy, Check
} from 'lucide-react'
import { SYMPTOMS } from '../../shared/triageSchema.js'

// ─────────────────────────────────────────────────────────────
// RISK CONFIGURATION
// ─────────────────────────────────────────────────────────────
const RISK_META = {
  HIGH:   { Icon: AlertOctagon,  bg: '#c8102e', label: 'HIGH RISK',   sub: 'Urgent referral required' },
  MEDIUM: { Icon: AlertTriangle, bg: '#c45c00', label: 'MEDIUM RISK', sub: 'Referral recommended' },
  LOW:    { Icon: CheckCircle,   bg: '#1a6b3a', label: 'LOW RISK',    sub: 'Monitor and educate' }
}

// ─────────────────────────────────────────────────────────────
// FACILITY TYPE MAPS  (module-level so every component can use them)
// ─────────────────────────────────────────────────────────────
const FACILITY_TYPE_LABEL = {
  primary:   'Primary',
  secondary: 'Secondary',
  tertiary:  'Tertiary'
}

const FACILITY_TYPE_COLOR = {
  primary:   '#1a6b3a',
  secondary: '#c45c00',
  tertiary:  '#0a3d6b'
}

// ─────────────────────────────────────────────────────────────
// REFERRAL LETTER GENERATOR
// ─────────────────────────────────────────────────────────────
function buildReferralLetter({ patient_name, patient_gender, age_months,
                                assessed_at, risk_level, risk_score,
                                referral, explanation, symptoms,
                                facility_name, facility_type }) {
  const ageYears  = Math.floor(age_months / 12)
  const ageMos    = age_months % 12
  const ageStr    = ageYears > 0
    ? `${ageYears} year${ageYears !== 1 ? 's' : ''} ${ageMos > 0 ? `${ageMos} month${ageMos !== 1 ? 's' : ''}` : ''}`.trim()
    : `${ageMos} month${ageMos !== 1 ? 's' : ''}`

  // Format gender for letter
  const genderStr = patient_gender && patient_gender !== 'unknown'
    ? patient_gender.charAt(0).toUpperCase() + patient_gender.slice(1)
    : 'Not recorded'

  const date = new Date(assessed_at || Date.now())
    .toLocaleDateString('en-GB', { day:'2-digit', month:'long', year:'numeric' })

  const symptomLines = SYMPTOMS
    .filter(s => symptoms?.[s.key])
    .map(s => `  • ${s.label}`)
    .join('\n') || '  • No symptoms reported'

  const facilityStr = facility_name
    ? `${facility_name}${facility_type ? ` (${FACILITY_TYPE_LABEL[facility_type]})` : ''}`
    : 'Not recorded'

  return `PAEDIATRIC CANCER TRIAGE REFERRAL LETTER
Generated by Nofom Triage Platform
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Date of Assessment: ${date}

PATIENT DETAILS
Patient Name : ${patient_name || 'Not provided'}
Age          : ${ageStr}
Gender       : ${genderStr}

ASSESSING FACILITY
Facility        : ${facilityStr}

TRIAGE RESULT
Risk Level   : ${risk_level}
Risk Score   : ${risk_score}
Assessed by  : Nofom Rule-Based Triage Engine v1

REFERRAL RECOMMENDATION
Action       : ${referral?.label || '—'}
Timeframe    : ${referral?.timeframe || '—'}
Facility Tier: ${referral?.facility_tier || '—'}

SYMPTOMS REPORTED
${symptomLines}

${referral?.special_notes?.length > 0
  ? `CLINICAL WARNINGS\n${referral.special_notes.map(n => `  ⚠ ${n}`).join('\n')}\n`
  : ''}
CLINICAL REASONING
${explanation?.map((e, i) => `${i + 1}. ${e}`).join('\n\n') || '—'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CLINICAL NOTICE: This letter was generated by a rule-based
triage assistant. It does not constitute a diagnosis. All
referral decisions must be confirmed by a qualified health
professional. Please attach clinical notes at the receiving
facility.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`
}

// ─────────────────────────────────────────────────────────────
// REFERRAL LETTER DRAWER
// ─────────────────────────────────────────────────────────────
function ReferralLetterDrawer({ result, onClose }) {
  const [copied, setCopied] = useState(false)
  const letter = buildReferralLetter(result)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(letter)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  const handlePrint = () => {
    const w = window.open('', '_blank')
    w.document.write(`<html><head><title>Nofom Referral Letter</title>
      <style>
        body { font-family: 'Courier New', monospace; padding: 40px;
               font-size: 13px; line-height: 1.6; color: #000; }
        pre  { white-space: pre-wrap; word-wrap: break-word; }
        @media print { body { padding: 20px; } }
      </style></head><body><pre>${letter}</pre></body></html>`)
    w.document.close()
    w.print()
  }

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 100,
      background: 'rgba(10,61,107,0.55)',
      display: 'flex', flexDirection: 'column',
      justifyContent: 'flex-end'
    }}
      onClick={e => { if (e.target === e.currentTarget) onClose() }}
    >
      <div style={{
        background: 'var(--color-surface)',
        borderRadius: '16px 16px 0 0',
        maxHeight: '85dvh',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden'
      }}>
        {/* Drawer handle */}
        <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between',
                      padding:'16px 16px 12px', borderBottom:'1px solid var(--color-border)',
                      flexShrink:0 }}>
          <div style={{ display:'flex', alignItems:'center', gap:8 }}>
            <FileText size={16} style={{ color:'var(--color-primary)' }} />
            <span style={{ fontWeight:700, fontSize:'0.9375rem',
                           color:'var(--color-text-primary)' }}>
              Referral Letter
            </span>
          </div>
          <button onClick={onClose} style={{
            background:'none', border:'none', cursor:'pointer',
            color:'var(--color-text-muted)', fontSize:'1.25rem',
            lineHeight:1, padding:'2px 6px', fontFamily:'var(--font-sans)'
          }}>×</button>
        </div>

        {/* Letter content */}
        <div style={{ flex:1, overflowY:'auto', padding:'16px' }}>
          <pre style={{
            fontFamily: '"IBM Plex Mono", "Courier New", monospace',
            fontSize: '0.75rem',
            lineHeight: 1.7,
            color: 'var(--color-text-primary)',
            background: 'var(--color-surface-alt)',
            borderRadius: 'var(--radius-md)',
            padding: '16px',
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word',
            margin: 0
          }}>
            {letter}
          </pre>
        </div>

        {/* Actions */}
        <div style={{
          display:'flex', gap:10, padding:'12px 16px 20px',
          borderTop:'1px solid var(--color-border)', flexShrink:0
        }}>
          <button onClick={handleCopy}
            className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
            {copied ? <Check size={15} /> : <Copy size={15} />}
            {copied ? 'Copied!' : 'Copy text'}
          </button>
          <button onClick={handlePrint}
            className="nf-btn nf-btn-primary" style={{ flex:1 }}>
            <FileText size={15} />
            Print / Save PDF
          </button>
        </div>
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// SHARED SLIDE NAV — bottom bar inside each card
// ─────────────────────────────────────────────────────────────
function SlideNav({ onPrev, prevLabel, onNext, nextLabel }) {
  const btn = {
    display:'flex', alignItems:'center', gap:5,
    background:'none', border:'none', cursor:'pointer',
    fontFamily:'var(--font-sans)', fontSize:'0.875rem',
    fontWeight:600, padding:'8px 4px',
    borderRadius:'var(--radius-md)',
    transition:'color 120ms'
  }
  return (
    <div style={{
      display:'flex', justifyContent:'space-between',
      paddingTop:12, marginTop:'auto',
      borderTop:'1px solid var(--color-border)', flexShrink:0
    }}>
      {onPrev
        ? <button style={{ ...btn, color:'var(--color-text-secondary)' }} onClick={onPrev}>
            <ChevronLeft size={16} />{prevLabel}
          </button>
        : <span/>}
      {onNext
        ? <button style={{ ...btn, color:'var(--color-accent)' }} onClick={onNext}>
            {nextLabel}<ChevronRight size={16} />
          </button>
        : <span/>}
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// SLIDE 1 — Risk score
// ─────────────────────────────────────────────────────────────
function Slide1({ result, goNext }) {
  const { risk_level, risk_score, max_possible_score,
          age_modifier, duration_label, override_applied,
          primary_count, patient_name, age_months, patient_gender, facility_name, facility_type } = result
  const meta  = RISK_META[risk_level] || RISK_META.LOW
  const Icon  = meta.Icon
  const pct   = Math.min(100, Math.round((risk_score / (max_possible_score || 200)) * 100))
  const ageYears = Math.floor(age_months / 12)
  const ageMos   = age_months % 12

  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100%', padding:'16px 16px 0' }}>
      <p style={{ margin:'0 0 14px', fontSize:'0.6875rem', fontWeight:700,
                  letterSpacing:'0.07em', textTransform:'uppercase',
                  color:'var(--color-text-muted)' }}>
        1 of 4 · Risk score
      </p>

      {/* Patient name bar */}
      <div style={{
        display:'flex', alignItems:'center', justifyContent:'space-between',
        background:'var(--color-surface-alt)',
        border:'1px solid var(--color-border)',
        borderRadius:'var(--radius-md)',
        padding:'10px 14px', marginBottom:12
      }}>
        <div>
          <p style={{ margin:0, fontWeight:700, fontSize:'1rem',
                      color:'var(--color-text-primary)' }}>
            {patient_name || 'Patient'}
          </p>
          <p style={{ margin:'2px 0 0', fontSize:'0.8125rem', color:'var(--color-text-muted)' }}>
            Age: {ageYears > 0 ? `${ageYears}y ` : ''}{ageMos > 0 ? `${ageMos}m` : ''}
            {ageYears === 0 && ageMos === 0 ? `${age_months} months` : ''}
            {patient_gender && patient_gender !== 'unknown'
              ? ` · ${patient_gender.charAt(0).toUpperCase() + patient_gender.slice(1)}`
              : ''}
          </p>
        </div>
        <div style={{
          width:42, height:42, borderRadius:'50%',
          background: meta.bg,
          display:'flex', alignItems:'center', justifyContent:'center',
          flexShrink:0
        }}>
          <Icon size={22} color="white" />
        </div>
      </div>

      {/* Risk badge */}
      <div style={{
        background: meta.bg, borderRadius:'var(--radius-lg)',
        padding:'20px', color:'white', marginBottom:12, position:'relative',
        overflow:'hidden', flexShrink:0
      }}>
        {/* Decorative circle */}
        <div style={{
          position:'absolute', top:-30, right:-20,
          width:120, height:120, borderRadius:'50%',
          background:'rgba(255,255,255,0.07)', pointerEvents:'none'
        }}/>
        <p style={{ margin:'0 0 2px', fontSize:'1.75rem', fontWeight:800,
                    letterSpacing:'-0.02em', lineHeight:1 }}>
          {meta.label}
        </p>
        <p style={{ margin:'4px 0 16px', fontSize:'0.9375rem', opacity:0.85 }}>
          {meta.sub}
        </p>
        <div style={{ display:'flex', justifyContent:'space-between',
                      fontSize:'0.75rem', opacity:0.75, marginBottom:5 }}>
          <span>Risk score</span>
          <span style={{ fontFamily:'var(--font-mono)', fontWeight:600 }}>
            {risk_score} / {max_possible_score || 200}
          </span>
        </div>
        <div style={{ height:8, background:'rgba(255,255,255,0.25)',
                      borderRadius:999, overflow:'hidden' }}>
          <div style={{
            height:'100%', background:'rgba(255,255,255,0.85)',
            borderRadius:999, width:`${pct}%`,
            transition:'width 0.8s cubic-bezier(0.16,1,0.3,1)'
          }}/>
        </div>
      </div>

      {/* Context chips */}
      <div style={{ display:'flex', gap:8, flexWrap:'wrap', marginBottom:12 }}>
        <span className="nf-chip">📅 {duration_label}</span>
        <span className="nf-chip">👶 {age_modifier?.label}</span>
        {facility_name && (
          <span className="nf-chip">
            🏥 {facility_name}
            {facility_type && (
              <span style={{ marginLeft:4, fontWeight:700,
                             color: FACILITY_TYPE_COLOR[facility_type] }}>
                · {FACILITY_TYPE_LABEL[facility_type]}
              </span>
            )}
          </span>
        )}
      </div>

      {/* Override notice */}
      {override_applied && (
        <div className="nf-alert nf-alert-warning" style={{ marginBottom:12 }}>
          <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }} />
          <span>
            Safety override: {primary_count} primary indicators present simultaneously
            forces HIGH risk regardless of score.
          </span>
        </div>
      )}

      <SlideNav onNext={goNext} nextLabel="Referral action" />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// SLIDE 2 — Referral action
// ─────────────────────────────────────────────────────────────
function Slide2({ referral, goNext, goPrev, onShowLetter }) {
  if (!referral) return null
  const accent = { danger:'var(--color-high)', warning:'var(--color-medium)',
                   success:'var(--color-low)' }[referral.color] || 'var(--color-accent)'

  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100%', padding:'16px 16px 0' }}>
      <p style={{ margin:'0 0 14px', fontSize:'0.6875rem', fontWeight:700,
                  letterSpacing:'0.07em', textTransform:'uppercase',
                  color:'var(--color-text-muted)' }}>
        2 of 4 · Referral action
      </p>

      {/* Action header */}
      <div style={{
        display:'flex', alignItems:'flex-start', gap:12,
        padding:'14px', marginBottom:12,
        background:'var(--color-surface-alt)',
        border:`1px solid var(--color-border)`,
        borderLeft:`4px solid ${accent}`,
        borderRadius:'var(--radius-md)'
      }}>
        <Building2 size={20} style={{ color:accent, flexShrink:0, marginTop:2 }} />
        <div>
          <p style={{ margin:0, fontWeight:700, fontSize:'1rem',
                      color:'var(--color-text-primary)' }}>
            {referral.label}
          </p>
          <p style={{ margin:'5px 0 3px', fontSize:'0.9375rem',
                      color:'var(--color-text-secondary)' }}>
            ⏱ {referral.timeframe}
          </p>
          <p style={{ margin:0, fontSize:'0.8125rem', color:'var(--color-text-muted)' }}>
            Facility level: <strong>{referral.facility_tier}</strong>
          </p>
        </div>
      </div>

      {/* Clinical warnings */}
      {referral.special_notes?.length > 0 && (
        <div style={{ display:'flex', flexDirection:'column', gap:8, marginBottom:12 }}>
          {referral.special_notes.map((note, i) => (
            <div key={i} className="nf-alert nf-alert-danger">
              <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }} />
              <span style={{ fontWeight:600, lineHeight:1.45 }}>{note}</span>
            </div>
          ))}
        </div>
      )}

      {(!referral.special_notes || referral.special_notes.length === 0) && (
        <div className="nf-alert nf-alert-info" style={{ marginBottom:12 }}>
          <span>No special clinical warnings for this symptom combination.</span>
        </div>
      )}

      {/* Generate letter button */}
      <button onClick={onShowLetter}
        style={{
          display:'flex', alignItems:'center', justifyContent:'center', gap:8,
          width:'100%', padding:'11px',
          background:'var(--color-primary-light)',
          border:`1.5px solid var(--color-accent)`,
          borderRadius:'var(--radius-md)',
          color:'var(--color-primary)', fontFamily:'var(--font-sans)',
          fontWeight:600, fontSize:'0.9rem', cursor:'pointer',
          marginTop:'auto', marginBottom:0, flexShrink:0
        }}>
        <FileText size={15} />
        Generate Referral Letter
      </button>

      <SlideNav onPrev={goPrev} prevLabel="Score" onNext={goNext} nextLabel="Steps to take" />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// SLIDE 3 — Steps to take
// ─────────────────────────────────────────────────────────────
function Slide3({ referral, goNext, goPrev }) {
  if (!referral) return null
  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100%', padding:'16px 16px 0' }}>
      <p style={{ margin:'0 0 14px', fontSize:'0.6875rem', fontWeight:700,
                  letterSpacing:'0.07em', textTransform:'uppercase',
                  color:'var(--color-text-muted)' }}>
        3 of 4 · Steps to take
      </p>

      <div style={{ flex:1, overflowY:'auto' }}>
        {referral.instructions.map((step, i) => (
          <div key={i} style={{
            display:'flex', gap:12, padding:'11px 0',
            borderBottom:'1px solid var(--color-border)',
            alignItems:'flex-start'
          }}>
            <div style={{
              flexShrink:0, width:26, height:26, borderRadius:'50%',
              background:'var(--color-primary-light)',
              color:'var(--color-primary)',
              fontSize:'0.8125rem', fontWeight:700,
              display:'flex', alignItems:'center', justifyContent:'center'
            }}>
              {i + 1}
            </div>
            <p style={{ margin:0, fontSize:'0.9375rem',
                        color:'var(--color-text-secondary)',
                        lineHeight:1.55, flex:1 }}>
              {step}
            </p>
          </div>
        ))}
      </div>

      <SlideNav onPrev={goPrev} prevLabel="Action"
                onNext={goNext} nextLabel="Why this result?" />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// SLIDE 4 — Why this result
// ─────────────────────────────────────────────────────────────
function Slide4({ result, goPrev, onDashboard, onNewAssessment }) {
  const { explanation, override_applied } = result
  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100%', padding:'16px 16px 0' }}>
      <p style={{ margin:'0 0 14px', fontSize:'0.6875rem', fontWeight:700,
                  letterSpacing:'0.07em', textTransform:'uppercase',
                  color:'var(--color-text-muted)' }}>
        4 of 4 · Why this result?
      </p>

      <div style={{ flex:1, overflowY:'auto' }}>
        {override_applied && (
          <div className="nf-alert nf-alert-warning" style={{ marginBottom:12 }}>
            <AlertTriangle size={14} style={{ flexShrink:0, marginTop:1 }} />
            <span>
              Safety override applied — 2+ primary indicators simultaneously
              forces HIGH risk regardless of individual scores.
            </span>
          </div>
        )}

        {explanation.map((line, i) => (
          <div key={i} style={{
            display:'flex', gap:10, padding:'9px 0',
            borderBottom:'1px solid var(--color-border)',
            alignItems:'flex-start'
          }}>
            <div style={{
              flexShrink:0, width:6, height:6, borderRadius:'50%',
              background:'var(--color-primary)', opacity:0.4, marginTop:8
            }}/>
            <p style={{ margin:0, fontSize:'0.9rem',
                        color:'var(--color-text-secondary)',
                        lineHeight:1.6, flex:1 }}>
              {line}
            </p>
          </div>
        ))}

        <div className="nf-disclaimer" style={{ margin:'12px 0 4px' }}>
          <strong>Clinical note:</strong> This tool assists decision-making and
          does not replace clinical judgement. All referral decisions should be
          confirmed by a qualified health professional.
        </div>
      </div>

      {/* End-of-flow CTA buttons */}
      <div style={{ display:'flex', gap:10, paddingTop:12,
                    marginTop:'auto', flexShrink:0 }}>
        <button onClick={onDashboard}
          className="nf-btn nf-btn-secondary" style={{ flex:1 }}>
          <ArrowLeft size={14} /> Dashboard
        </button>
        <button onClick={onNewAssessment}
          className="nf-btn nf-btn-primary" style={{ flex:1 }}>
          <PlusCircle size={14} /> New
        </button>
      </div>
      {/* Keep spacing at bottom */}
      <div style={{ height:16, flexShrink:0 }} />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// DOT INDICATORS
// ─────────────────────────────────────────────────────────────
function Dots({ current, total, goTo }) {
  return (
    <div style={{
      display:'flex', justifyContent:'center',
      alignItems:'center', gap:5,
      padding:'8px 0 10px', flexShrink:0,
      background:'var(--color-surface)',
      borderTop:'1px solid var(--color-border)'
    }}>
      {Array.from({ length: total }).map((_, i) => (
        <button key={i} onClick={() => goTo(i)}
          aria-label={`Card ${i + 1}`}
          style={{
            width: i === current ? 20 : 7, height:7,
            borderRadius:999,
            background: i === current
              ? 'var(--color-primary)'
              : 'var(--color-border-strong)',
            border:'none', cursor:'pointer', padding:0,
            transition:'width 0.25s ease, background 0.2s'
          }}
        />
      ))}
    </div>
  )
}

// ─────────────────────────────────────────────────────────────
// MAIN PAGE
// ─────────────────────────────────────────────────────────────
const TOTAL = 4

export default function TriageResult() {
  const navigate         = useNavigate()
  const lastTriageResult = useAppStore(s => s.lastTriageResult)
  const viewportRef      = useRef(null)
  const [current, setCurrent]     = useState(0)
  const [showLetter, setShowLetter] = useState(false)

  useEffect(() => {
    if (!lastTriageResult) navigate('/')
  }, [lastTriageResult])

  if (!lastTriageResult) return null

  const { referral } = lastTriageResult

  // ── Programmatic scroll ─────────────────────────────────
  const goTo = useCallback((i) => {
    const el = viewportRef.current
    if (!el) return
    el.scrollTo({ left: i * el.offsetWidth, behavior: 'smooth' })
    setCurrent(i)
  }, [])

  const goNext = useCallback(() => goTo(Math.min(current + 1, TOTAL - 1)), [current, goTo])
  const goPrev = useCallback(() => goTo(Math.max(current - 1, 0)),         [current, goTo])

  const handleScroll = useCallback(() => {
    const el = viewportRef.current
    if (!el) return
    const i = Math.round(el.scrollLeft / el.offsetWidth)
    if (i !== current) setCurrent(i)
  }, [current])

  return (
    <div style={{
      height: '100dvh',
      display: 'flex',
      flexDirection: 'column',
      background: 'var(--color-surface-alt)',
      fontFamily: 'var(--font-sans)',
      overflow: 'hidden'
    }}>
      <Header />

      {/* Progress bar */}
      <div style={{ height:3, background:'var(--color-border)', flexShrink:0, position:'relative' }}>
        <div style={{
          position:'absolute', top:0, left:0, height:'100%',
          background:'var(--color-primary)',
          width:`${((current + 1) / TOTAL) * 100}%`,
          transition:'width 0.35s ease',
          borderRadius:'0 999px 999px 0'
        }}/>
      </div>

      {/* ── SWIPE VIEWPORT ── */}
      <div
        ref={viewportRef}
        onScroll={handleScroll}
        style={{
          flex: 1,
          display: 'flex',
          overflowX: 'scroll',
          overflowY: 'hidden',
          scrollSnapType: 'x mandatory',
          WebkitOverflowScrolling: 'touch',
          scrollbarWidth: 'none',
          msOverflowStyle: 'none',
        }}
      >
        {[
          <Slide1 key="s1" result={lastTriageResult} goNext={goNext} />,
          <Slide2 key="s2" referral={referral} goNext={goNext} goPrev={goPrev}
                  onShowLetter={() => setShowLetter(true)} />,
          <Slide3 key="s3" referral={referral} goNext={goNext} goPrev={goPrev} />,
          <Slide4 key="s4" result={lastTriageResult} goPrev={goPrev}
                  onDashboard={() => navigate('/')}
                  onNewAssessment={() => navigate('/triage/new')} />
        ].map((slide, i) => (
          <div key={i} style={{
            flex: '0 0 100%',
            width: '100%',
            maxWidth: 520,
            height: '100%',
            overflowY: 'hidden',
            scrollSnapAlign: 'start',
            display: 'flex',
            flexDirection: 'column',
            background: 'var(--color-surface)',
            borderRight: '1px solid var(--color-border)'
          }}>
            {slide}
          </div>
        ))}
      </div>

      <Dots current={current} total={TOTAL} goTo={goTo} />

      {/* Referral letter drawer */}
      {showLetter && (
        <ReferralLetterDrawer
          result={lastTriageResult}
          onClose={() => setShowLetter(false)}
        />
      )}
    </div>
  )
}
